baseURL: "https://www.chandraharsha111.com"
languageCode: "en-us"
title: "Chandra Harsha Jupalli"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog Posts
      url: /posts
      weight: 1
    # - identifier: Recent Projects
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    # Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Harsha's personal website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Chandra Harsha Jupalli" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro:  "Hi there 👋, I am "
    title: ""
    subtitle: "Chandra Harsha Jupalli"
    content: "Software Engineer with experience in Java, RESTful webservices, Microservices, Platfrom Engineering, and Devops." 
    image: /images/profilephoto.png
    bottomImage:
      enable: true
    roundImage: false # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/17BkKeRB1thNlUQtIVUO-sVKlRVcAfdGM/view?usp=drive_link"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/chandraharsha111/
        - icon: fab fa-twitter
          url: https://twitter.com/harsha1038/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/cjupa/
      
  # About
  about:
    enable: true
    title: "About"
    # Fix the shape and deliberate wrong filename
    image: "/images/profilepoto.png"
    roundImage: false
    content: |-
       Syracuse University graduate with a Masters in Computer Engineering. Currently working as a Software Developer in a Platform Engineering team developing and deploying microservices at Oracle Health and AI. 
       
       Experienced in developing backend applications using Java, developing CI-CD pipelines, and deploying microservices using Kubernetes and HelmCharts. 
       Developed Ruby scripts to facilitate the configuration, validation, CVE management and service deployments.  
    skills:
      enable: true
      title: "Here are a few technologies and tools I've been working with recently"
      items: 
        - "Java"
        - "Apache Maven"
        - "Ruby"
        - "Kubernetes"
        - "Helm Charts"
        - "OCI"
        - "AWS"
        - "Jenkins"
        - "JDBC"
        - "SQL"
        - "Splunk"
        - "NewRelic"
        - "Web Services(REST)"
        - "API Design"
                
  # Experience
  experience:
    enable: true
    title: "Professional Experience"
    items:
      - job: "Associate Senior Software Engineer"
        company: "Oracle"
        companyUrl: "https://www.oracle.com/"
        date: "October 2022 - present"
        # featuredLink:
        #  enable: true
        #  name: "View the project"
        #  url: "https://example.com"
        info:
          enable: true
          content: Working as an associate senior software engineer at Oracle
        content: | 
         
          - Designed and implemented tenant-specific namespaces to simplify microservice deployments using Kubernetes
          - Implemented new features and collaborated on a Java-based development platform to provide a consistent means of developing microservices and handled central cloud deployments
          - Managed platform-level dependencies; Identified and fixed security vulnerabilities or CVEs for microservices
          - Worked on a Cadence bundles feature to manage about 10 enterprise stack dependencies for 200 enterprise Java services
          - Implemented features related to migrating Millennium web services to Oracle Cloud
          - Automated the API review process by creating a Jenkins Job to assign approved API reviewers
          - Worked on support roles to help answer platform related questions for over 200 service teams

      - job: "Software Developer"
        company: "Cerner Corporation "
        companyUrl: "https://www.cerner.com/"
        date: "June 2018 - September 2022"
        info:
          enable: true
          content: Worked as a software engineer for 4 years at Cerner in Kansas City, MO
        content: |

          - Developed automation scripts and functionality that facilitated shadowing and canarying micro servicemigrations
          - Implemented Auth support for sidecar service, which takes in SRV request and casts it to HTTP, and deployed the service using Helm to Kubernetes
          -  Led API reviews across micro services to eliminate redundant APIs in Millennium, an EHR product
          - Leveraged Jenkins to create multibranched pipelines across several libraries to improve CI-CD
          - Created endpoints in Spring MVC to add export functionality, implemented CRUD operations using Hibernate (HQL),
          - Implemented UI using HTML, CSS, JavaScript, jQuery Data Table API to create responsive web pages
          - Mentored new associates who joined between Aug 2020 to Dec 2022

      - job: "Program Analyst"
        company: "Cognizant"
        companyUrl: "https://www.cognizant.com/us/en"
        date: "Aug 2015 - June 2016"
        info:
          enable: true
          content: Worked as a Program Analyst in Hyderabad, India for 1 year at Cognizant
        content: |
      
          - Formulated and Implemented unit tests in .Net Platform using FAKES in C# to ensure code functionality and improved code coverage from 60 to 90 percent
          - Collaborated with team members via Agile ceremonies and Scaled Agile Framework (SAFe)
  
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Executive MBA in Information Technology"
        school:
          name: "Ottawa University, Kansas City, Kansas"
          url: "https://www.ottawa.edu/"
        date: "June 2021 - June 2023"
        GPA: "3.92 out of 4.0"
        content: |-
          Course Work
            - Managerial Finance 
            - Managerial Accounting
            - Business Policies and Strategy
            - Organizational Behavior Theory
            - Information Systems
            - System Analytics and Enterprise Management
      - title: "Master of Science in Computer Engineering"
        school:
          name: "Syracuse University, Syracuse, New York"
          url: "https://www.ottawa.edu/"
        date: "August 2016 - May 2018"
        GPA: "3.7 out of 4.0"
        content: |-
          Course Work
            - Software Modelling & Analysis
            - Advanced Data Structures
            - Object Oriented Design
            - Android Programming
            - Design Patterns   
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "SRM University, Chennai, India"
          url: "https://www.ottawa.edu/"
        date: "June 2011 - May 2015"
        GPA: "9.3 out of 10.0"
        content: |-
          Course Work
            - Data Structures
            - Java Programming 
            - Operating Systems
            - Computer Networking 
            - Computer Security
     

  # Achievements
  # achievements:
  #  enable: true
    # title: "Custom Name"
    # items:
    #  - title: Google kickstart runner
    #    content: I solved all problems with optimal solution.
    #    url: https://example.com
    #    image: /images/achievment.jpg
      
  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: University Database
        content: Design and implementation of 3NF normalized database schema in SQL Server
        image: "/images/UniversityDB.png"
        badges:
          - "SQL Server"
          - "SQL Functions"
          - "SQL Triggers"
          - "MS Visio"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/chandraharsha111/University-Database/tree/master
         
  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: chandraharsha111@gmail.com
    btnName: Mail me
    formspree:
       enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "posts"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      
  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>